server:
  port: 80

database:
  url: jdbc:postgresql://192.168.1.208:5432/postgres
  user: postgres
  password: 12345

spring:
  application:
    name: small-business
  datasource:
    url: ${database.url}
    username: ${database.user}
    password: ${database.password}
    hikari:
      max-lifetime: 600000 # 10 minutes
  liquibase:
    change-log: classpath:db/dbchangelog.xml
    driver-class-name: org.postgresql.Driver
    url: ${database.url}
    user: ${database.user}
    password: ${database.password}